name: Build and publish flask-pypprof

on:
  release:
    types: [ published ]

jobs:
  publish-flask-pypprof-package:
    runs-on: ubuntu-latest
#    permissions:
#      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Publish PyPi package
        uses: celsiusnarhwal/poetry-publish@v2
        with:
          python-version: 3.10.4
          poetry-version: 1.5.1
          token: ${{ secrets.PYPI_API_TOKEN }}
#          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}