name: Build and publish flask-pypprof

on:
  release:
    types: [ published ]

jobs:
  publish-flask-pypprof-package:
    runs-on: ubuntu-latest
#    permissions:
#      contents: write
    steps:
      - name: Publish PyPi package
        uses: celsiusnarhwal/poetry-publish@v2
        with:
          poetry-version: 1.5.1
          token: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}